# Generated by Django 4.1.3 on 2023-01-11 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_product_cartitem_product1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantity',
            new_name='quantit',
        ),
    ]
