# Generated by Django 4.1.3 on 2023-01-11 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_quantity_cartitem_quantit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantit',
            new_name='quantity',
        ),
    ]
